---
apiVersion: v1
kind: Pod
metadata:
  name: fresco-nginx-pod
spec:
  containers:
    - name: fresco-nginx-container
      image: nginx
      env:
      - name: SERVER_URL_ENV
        valueFrom: 
          configMapKeyRef:
            name: fresco-config
            key: SERVER_URL
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: fresco-secret
            key: user
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: fresco-secret
            key: pass      
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
        - mountPath: "/etc/test"
          name: secret-volume       
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: fresco-pvc
    - name: secret-volume
      secret:
        secretName: fresco-secret                    
